OPCODE = {
    "ADD": {"format": 3, "opcode": 0x18},
    "ADDF": {"format": 3, "opcode": 0x58},
    "ADDR": {"format": 2, "opcode": 0x90},
    "AND": {"format": 3, "opcode": 0x40},
    "CLEAR": {"format": 2, "opcode": 0xB4},
    "COMP": {"format": 3, "opcode": 0x28},
    "COMPF": {"format": 3, "opcode": 0x88},
    "COMPR": {"format": 2, "opcode": 0xA0},
    "DIV": {"format": 3, "opcode": 0x24},
    "DIVF": {"format": 3, "opcode": 0x64},
    "DIVR": {"format": 2, "opcode": 0x9C},
    "FIX": {"format": 1, "opcode": 0xC4},
    "FLOAT": {"format": 1, "opcode": 0xC0},
    "HALT": {"format": 1, "opcode": 0xE4},
    "HIO": {"format": 1, "opcode": 0xF4},
    "J": {"format": 3, "opcode": 0x3C},
    "JEQ": {"format": 3, "opcode": 0x30},
    "JGT": {"format": 3, "opcode": 0x34},
    "JLT": {"format": 3, "opcode": 0x38},
    "JNE": {"format": 3, "opcode": 0x8C},
    "JSUB": {"format": 3, "opcode": 0x48},
    "LDA": {"format": 3, "opcode": 0x00},
    "LDB": {"format": 3, "opcode": 0x68},
    "LDCH": {"format": 3, "opcode": 0x50},
    "LDF": {"format": 3, "opcode": 0x70},
    "LDL": {"format": 3, "opcode": 0x08},
    "LDS": {"format": 3, "opcode": 0x6C},
    "LDT": {"format": 3, "opcode": 0x74},
    "LDX": {"format": 3, "opcode": 0x04},
    "LPS": {"format": 3, "opcode": 0xD0},
    "MUL": {"format": 3, "opcode": 0x20},
    "MULF": {"format": 3, "opcode": 0x60},
    "MULR": {"format": 2, "opcode": 0x98},
    "NORM": {"format": 1, "opcode": 0xC8},
    "OR": {"format": 3, "opcode": 0x44},
    "RD": {"format": 3, "opcode": 0xD8},
    "RMO": {"format": 2, "opcode": 0xAC},
    "RSUB": {"format": 3, "opcode": 0x4C},
    "SHIFTL": {"format": 2, "opcode": 0xA4},
    "SHIFTR": {"format": 2, "opcode": 0xA8},
    "SIO": {"format": 1, "opcode": 0xF0},
    "SSK": {"format": 3, "opcode": 0xEC},
    "STA": {"format": 3, "opcode": 0x0C},
    "STB": {"format": 3, "opcode": 0x78},
    "STCH": {"format": 3, "opcode": 0x54},
    "STF": {"format": 3, "opcode": 0x80},
    "STI": {"format": 3, "opcode": 0xD4},
    "STL": {"format": 3, "opcode": 0x14},
    "STS": {"format": 3, "opcode": 0x7C},
    "STSW": {"format": 3, "opcode": 0xE8},
    "STT": {"format": 3, "opcode": 0x84},
    "STX": {"format": 3, "opcode": 0x10},
    "SUB": {"format": 3, "opcode": 0x1C},
    "SUBF": {"format": 3, "opcode": 0x5C},
    "SUBR": {"format": 2, "opcode": 0x94},
    "SVC": {"format": 2, "opcode": 0xB0},
    "TD": {"format": 3, "opcode": 0xE0},
    "TIO": {"format": 3, "opcode": 0xF8},
    "TIX": {"format": 3, "opcode": 0x2C},
    "TIXR": {"format": 2, "opcode": 0xB8},
    "WD": {"format": 3, "opcode": 0xDC},
}

DIRECTIVE = {
    "START": {"format": 2},
    "END": {"format": 2},
    "BYTE": {"format": 2},
    "WORD": {"format": 2},
    "RESB": {"format": 2},
    "RESW": {"format": 2},
    "FLOA": {"format": 2},
    "RESF": {"format": 2},
    "USE": {"format": 2},
    "ORG": {"format": 2},
    "LTORG": {"format": 2},
    "EXTDEF": {"format": 2},
    "EXTREF": {"format": 2},
    "EQU": {"format": 2},
    "BASE": {"format": 2},
    "CSECT": {"format": 2},
    "MACRO": {"format": 2},
    "MEND": {"format": 2},
}
